variable "profile" {}
variable "region" {}
variable "vpc_cidr" {}
variable "pubsub1" {}
variable "pubsub2" {}
variable "prvsub1" {}
variable "prvsub2" {}
variable "allow_all_IP" {}
variable "az1" {}
variable "az2" {}
variable "domain" {}
variable "domain2" {}
variable "domain-jenkins" {}
variable "domain-stage" {}
variable "domain-prod" {}
variable "ami-ubuntu" {}
variable "instance_type" {}
variable "instance_type2" {}
variable "subnet-id" {}
variable "sonarqube-sg" {}
variable "keypair" {}
variable "ami-redhat" {}
variable "newrelic-license-key" {}
variable "newrelic-id" {}
