variable "profile" {}
variable "region" {}
variable "vpc_cidr" {}
variable "pubsub1" {}
variable "pubsub2" {}
variable "prvsub1" {}
variable "prvsub2" {}
variable "allow_all_IP" {}
variable "az1" {}
variable "az2" {}
