variable "ami" {}
variable "instance-type" {}
variable "stage-SG-ID" {}
variable "keypair" {}
variable "stage-asg-name" {}
variable "vpc-zone-identifier" {}
variable "tg-arn" {}
variable "asg-policy" {}
variable "nexus-ip" {}
variable "newrelic-user-licence" {}
variable "newrelic-acct-id" {}